name: ALTEN Frontend DEV CI&CD setup
on:
  push:  
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v1
    - name: Install Node.js
      uses: actions/setup-node@v1
      with:
        node-version: '12.x'
        
     - name: deploy
      run: npm install        
    - name: Notify dedicated teams channel
      uses: jdcargile/ms-teams-notification@v1.3
      with:
        github-token: ${{ github.token }} # this will use the runner's token.
        ms-teams-webhook-uri: ${{ secrets.MS_TEAMS_WEBHOOK_URI }}
        notification-summary: deployment notification 
        notification-color: 17a2b8
        timezone: Asia/Singapore